/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestWorkshopRouteImport } from './routes/request.workshop'
import { Route as RequestLabSpaceRouteImport } from './routes/request.lab-space'
import { Route as RequestInstitutionalRouteImport } from './routes/request.institutional'
import { Route as RequestFabricationRouteImport } from './routes/request.fabrication'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as RequestSuccessIdRouteImport } from './routes/request.success.$id'
import { Route as ApiPublicRequestSubmitRouteImport } from './routes/api/public/request-submit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestWorkshopRoute = RequestWorkshopRouteImport.update({
  id: '/request/workshop',
  path: '/request/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLabSpaceRoute = RequestLabSpaceRouteImport.update({
  id: '/request/lab-space',
  path: '/request/lab-space',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestInstitutionalRoute = RequestInstitutionalRouteImport.update({
  id: '/request/institutional',
  path: '/request/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestFabricationRoute = RequestFabricationRouteImport.update({
  id: '/request/fabrication',
  path: '/request/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSuccessIdRoute = RequestSuccessIdRouteImport.update({
  id: '/request/success/$id',
  path: '/request/success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRequestSubmitRoute = ApiPublicRequestSubmitRouteImport.update({
  id: '/api/public/request-submit',
  path: '/api/public/request-submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/request/fabrication': typeof RequestFabricationRoute
  '/request/institutional': typeof RequestInstitutionalRoute
  '/request/lab-space': typeof RequestLabSpaceRoute
  '/request/workshop': typeof RequestWorkshopRoute
  '/api/public/request-submit': typeof ApiPublicRequestSubmitRoute
  '/request/success/$id': typeof RequestSuccessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/request/fabrication': typeof RequestFabricationRoute
  '/request/institutional': typeof RequestInstitutionalRoute
  '/request/lab-space': typeof RequestLabSpaceRoute
  '/request/workshop': typeof RequestWorkshopRoute
  '/api/public/request-submit': typeof ApiPublicRequestSubmitRoute
  '/request/success/$id': typeof RequestSuccessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/request/fabrication': typeof RequestFabricationRoute
  '/request/institutional': typeof RequestInstitutionalRoute
  '/request/lab-space': typeof RequestLabSpaceRoute
  '/request/workshop': typeof RequestWorkshopRoute
  '/api/public/request-submit': typeof ApiPublicRequestSubmitRoute
  '/request/success/$id': typeof RequestSuccessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/health'
    | '/request/fabrication'
    | '/request/institutional'
    | '/request/lab-space'
    | '/request/workshop'
    | '/api/public/request-submit'
    | '/request/success/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/health'
    | '/request/fabrication'
    | '/request/institutional'
    | '/request/lab-space'
    | '/request/workshop'
    | '/api/public/request-submit'
    | '/request/success/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/health'
    | '/request/fabrication'
    | '/request/institutional'
    | '/request/lab-space'
    | '/request/workshop'
    | '/api/public/request-submit'
    | '/request/success/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RequestFabricationRoute: typeof RequestFabricationRoute
  RequestInstitutionalRoute: typeof RequestInstitutionalRoute
  RequestLabSpaceRoute: typeof RequestLabSpaceRoute
  RequestWorkshopRoute: typeof RequestWorkshopRoute
  ApiPublicRequestSubmitRoute: typeof ApiPublicRequestSubmitRoute
  RequestSuccessIdRoute: typeof RequestSuccessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/workshop': {
      id: '/request/workshop'
      path: '/request/workshop'
      fullPath: '/request/workshop'
      preLoaderRoute: typeof RequestWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/lab-space': {
      id: '/request/lab-space'
      path: '/request/lab-space'
      fullPath: '/request/lab-space'
      preLoaderRoute: typeof RequestLabSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/institutional': {
      id: '/request/institutional'
      path: '/request/institutional'
      fullPath: '/request/institutional'
      preLoaderRoute: typeof RequestInstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/fabrication': {
      id: '/request/fabrication'
      path: '/request/fabrication'
      fullPath: '/request/fabrication'
      preLoaderRoute: typeof RequestFabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/success/$id': {
      id: '/request/success/$id'
      path: '/request/success/$id'
      fullPath: '/request/success/$id'
      preLoaderRoute: typeof RequestSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/request-submit': {
      id: '/api/public/request-submit'
      path: '/api/public/request-submit'
      fullPath: '/api/public/request-submit'
      preLoaderRoute: typeof ApiPublicRequestSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  RequestFabricationRoute: RequestFabricationRoute,
  RequestInstitutionalRoute: RequestInstitutionalRoute,
  RequestLabSpaceRoute: RequestLabSpaceRoute,
  RequestWorkshopRoute: RequestWorkshopRoute,
  ApiPublicRequestSubmitRoute: ApiPublicRequestSubmitRoute,
  RequestSuccessIdRoute: RequestSuccessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
